// Client_Vue/src/components/BookATableForm/BookATableForm.vue
<template>
  <a-form
    :wrapperCol="{ flex: 1 }"
    labelAlign="left"
    labelWrap
    layout="vertical"
    name="wrap"
  >
    <CustomInput
      :rules="[{ required: true }]"
      label="Date"
      name="Date"
      type="date"
    />
    <CustomInput
      :rules="[{ required: true }]"
      label="Time"
      name="Time"
      type="time"
    />
    <a-form-item
      :rules="[{ required: true }]"
      label="Party Size"
      name="Party Size"
    >
      <a-input-number
        :min="1"
        class="base-input w-full flex items-center"
        type="number"
      ></a-input-number>
    </a-form-item>
    <a-form-item>
      <FormButton
        class="bg-primary w-full"
        htmlType="submit"
        title="Book now"
      />
    </a-form-item>
  </a-form>
</template>

<script lang="ts" setup>
import FormButton from "../FormButton/FormButton.vue";
import CustomInput from "../CustomInput/CustomInput.vue";
</script>

<style lang="scss" scoped></style>

// Client_React/src/components/BookATableForm/BookATableForm.tsx
import React from "react";
import CustomInput from "../CustomInput/CustomInput.tsx";
import FormButton from "../FormButton/FormButton.tsx";
import { Form, InputNumber } from "antd";

const BookATableForm = (): React.ReactNode => {
  const [form] = Form.useForm();

  return (
    <Form
      name="wrap"
      labelAlign="left"
      form={form}
      labelWrap
      wrapperCol={{ flex: 1 }}
    >
      <CustomInput
        rules={[{ required: true }]}
        label="Email"
        type="email"
        name="Email"
      />
      <CustomInput
        rules={[{ required: true }]}
        label="Password"
        type="password"
        name="Password"
      />

      <Form.Item
        rules={[{ required: true }]}
        label="Party Size"
        name="Party Size"
        layout="vertical"
      >
        <InputNumber
          min={1}
          variant="filled"
          className="base-input w-full flex items-center"
          type="number"
        />
      </Form.Item>
      <Form.Item>
        <FormButton
          htmlType="submit"
          className="bg-primary w-full"
          title="Log in"
        />
      </Form.Item>
    </Form>
  );
};

export default BookATableForm;
