// Client_React/src/pages/Home/index.tsx
import ItalianCuisine from "./ItalianCuisine";
import OurPopularMenu from "./OurPopularMenu";
import ReserveATable from "./ReserveATable";
import WelcomeToDelizioso from "./WelcomeToDelizioso";

const HomePage = (): React.ReactNode => {
  return (
    <main>
      <ItalianCuisine />
      <WelcomeToDelizioso />
      <OurPopularMenu />
      <ReserveATable />
    </main>
  );
};

export default HomePage;

// Client_Vue/src/pages/Home/index.vue
<template>
  <main>
    <ItalianCuisine />
    <WelcomeToDelizioso />
    <OurPopularMenu />
    <ReserveATable />
  </main>
</template>

<script lang="ts" setup>
import ItalianCuisine from "./ItalianCuisine.vue";
import WelcomeToDelizioso from "./WelcomeToDelizioso.vue";
import OurPopularMenu from "./OurPopularMenu.vue";
import ReserveATable from "./ReserveATable.vue";
</script>

<style lang="scss" scoped></style>
