// Client_Vue/src/components/CustomButton/CustomButton.vue
<template>
  <a-button
    :class="`base-button rounded-[162.94px] ${props.class}`"
    :htmlType="props.htmlType ? props.htmlType : 'button'"
    :type="props.type ? props.type : 'primary'"
  >
    {{ props.title }}
    <slot v-if="!props.title"></slot>
  </a-button>
</template>

<script lang="ts" setup>
import type { ButtonPropsType } from "./customButton.types";

const props = defineProps<ButtonPropsType>();
</script>

// Client_React/src/components/CustomButton/CustomButton.tsx
import React from "react";
import { Button } from "antd";
import { ButtonPropsType } from "./customButton.types";
const CustomButton: React.FC<ButtonPropsType> = ({
  type,
  htmlType,
  className,
  title,
  onClick,
}) => {
  return (
    <Button
      type={type ? type : "primary"}
      htmlType={htmlType ? htmlType : "button"}
      className={`base-button rounded-[162.94px] ${className}`}
      onClick={onClick}
    >
      {title}
    </Button>
  );
};

export default CustomButton;
