// Client_Vue/src/components/FormButton/FormButton.vue
<template>
  <a-button
    :type="props.type ? props.type : 'primary'"
    :htmlType="props.htmlType ? props.htmlType : 'button'"
    :class="`base-button rounded-[10px] ${props.class}`"
  >
    {{ props.title }}
  </a-button>
</template>

<script lang="ts" setup>
import { defineProps } from "vue";
import { FormButtonPropsType } from "./formButton.types";

const props = defineProps<FormButtonPropsType>();
</script>

<style lang="scss" scoped></style>

// Client_React/src/components/FormButton/FormButton.tsx
import React from "react";
import { Button } from "antd";
import { FormButtonPropsType } from "./formButton.types";
const FormButton: React.FC<FormButtonPropsType> = ({
  type,
  htmlType,
  className,
  title,
  onClick,
}) => {
  return (
    <Button
      type={type ? type : "primary"}
      htmlType={htmlType ? htmlType : "button"}
      className={`base-button rounded-[10px] ${className}`}
      onClick={onClick}
    >
      {title}
    </Button>
  );
};

export default FormButton;
