// Client_Vue/src/components/Categories/Categories.vue
<template>
  <div class="flex justify-between gap-5 md:gap-10 my-20 overflow-x-auto">
    <CustomButton
      v-for="category in categories"
      :key="category.id"
      :class="`
        flex-grow py-7 px-10 md:px-0
        ${
          category.id === activeCategoryId
            ? 'bg-[#311F09] text-[#FFFFFF]'
            : 'bg-gray-50 text-[#311F09]'
        }
      `"
      :title="category.title"
      @click="categoryClickHandler(category.id)"
    />
  </div>
</template>

<script lang="ts" setup>
import { type Ref, ref } from "vue";
import type { CategoryType } from "./categories.types.ts";
import CustomButton from "../CustomButton/CustomButton.vue";

const activeCategoryId: Ref<number> = ref(1);
const categories: CategoryType[] = [
  { id: 1, title: "All category" },
  { id: 2, title: "Dinner" },
  { id: 3, title: "Lunch" },
  { id: 4, title: "Dessert" },
  { id: 5, title: "Drink" },
];

const categoryClickHandler = (id: number) => (activeCategoryId.value = id);
</script>

<style lang="scss" scoped></style>

// Client_React/src/components/Categories/Categories.tsx
import React, { memo, useState } from "react";
import { CategoryType } from "./categories.types";
import CustomButton from "../CustomButton/CustomButton";

const Categories = (): React.ReactNode => {
  const [activeCategoryId, setActiveCategoryId] = useState<number>(1);
  const categories: CategoryType[] = [
    { id: 1, title: "All catagory" },
    { id: 2, title: "Dinner" },
    { id: 3, title: "Lunch" },
    { id: 4, title: "Dessert" },
    { id: 5, title: "Drink" },
  ];

  const changeActiveCategory = (categoryId: number): void => {
    setActiveCategoryId(categoryId);
  };

  const categoryClickHandler = (category: CategoryType): void => {
    changeActiveCategory(category.id);
  };

  return (
    <div className="flex justify-between gap-5 md:gap-10 my-20 overflow-x-auto">
      {categories.map((category) => (
        <CustomButton
          key={category.id}
          title={category.title}
          onClick={() => categoryClickHandler(category)}
          className={`
          flex-grow py-7 px-10 md:px-0
          ${
            category.id === activeCategoryId
              ? "bg-[#311F09] text-[#FFFFFF]"
              : "bg-gray-50 text-[#311F09]"
          }
        `}
        />
      ))}
    </div>
  );
};

export default memo(Categories);
